"""Generates a realistic 90-day daily price history per catalog product.

Replaces the frontend's on-the-fly 4-point straight-line synthesis
(`getOrSynthesizePriceHistory`'s fallback branch) with an actual generated
dataset: daily points, a random walk with mean reversion, a couple of
genuine flash-sale dips, and — for roughly half the catalog — a price at
some point in the window *below* today's, so "Lowest price in 90 days"
doesn't trivially light up on every single card. The frontend just renders
this; it does no price-history math of its own anymore.

Deterministic per product id (seeded), so re-running produces the same
dataset — matches every other generator in this directory.
"""

from __future__ import annotations

import json
import random
import re
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRODUCTS_TS = ROOT / "src" / "data" / "products.ts"
OUTPUT_TS = ROOT / "src" / "data" / "priceHistory.generated.ts"

DAYS = 90


def load_products() -> list[dict]:
    content = PRODUCTS_TS.read_text(encoding="utf-8")
    pattern = re.compile(
        r'id:\s*"(p-\d+)".*?category:\s*"(\w+)".*?mrp:\s*(\d+).*?sellingPrice:\s*(\d+)',
        re.S,
    )
    return [
        {"id": pid, "category": category, "mrp": int(mrp), "selling_price": int(sp)}
        for pid, category, mrp, sp in pattern.findall(content)
    ]


def generate_series(product: dict, today: date) -> list[dict]:
    rng = random.Random(product["id"])
    current = product["selling_price"]
    mrp = product["mrp"]

    # Whether this product's price today is genuinely the 90-day low (~55% of
    # the catalog) or dipped lower at some point and has since recovered —
    # a catalog where every card claims "lowest price" isn't credible.
    is_today_the_low = rng.random() < 0.55

    # Walk backwards from today so the series always ends exactly at the
    # product's real current price, then reverse.
    prices = [current]
    price = float(current)
    # Headroom the walk is allowed to drift into, capped by MRP.
    ceiling = min(mrp * 0.98, current * 1.35)

    # 1-2 flash-sale windows: a handful of days sitting noticeably lower,
    # simulating a past sale event rather than smooth noise everywhere.
    sale_windows = set()
    for _ in range(rng.randint(1, 2)):
        start = rng.randint(10, DAYS - 10)
        for offset in range(rng.randint(2, 4)):
            sale_windows.add(start + offset)

    floor_for_history = current * 0.97 if is_today_the_low else current * 0.80

    for day_offset in range(1, DAYS):
        in_sale = day_offset in sale_windows
        # Mean-reverting random walk: drifts toward `ceiling` over the long
        # run (prices generally *were* higher in the past) with daily noise.
        drift = (ceiling - price) * 0.015
        noise = rng.gauss(0, price * 0.006)
        price = price + drift + noise
        if in_sale:
            price *= rng.uniform(0.90, 0.95)
        price = max(floor_for_history, min(price, ceiling))
        prices.append(round(price))

    prices.reverse()  # oldest -> newest, ending at `current`
    prices[-1] = current  # float drift guard: today must equal the real price

    if not is_today_the_low:
        # Force at least one point genuinely below today's price so the
        # "lowest in 90 days" badge correctly stays off for this product.
        dip_index = rng.randint(5, DAYS - 15)
        prices[dip_index] = max(1, round(current * rng.uniform(0.90, 0.97)))

    start_date = today - timedelta(days=DAYS - 1)
    return [
        {"date": (start_date + timedelta(days=i)).isoformat(), "price": p}
        for i, p in enumerate(prices)
    ]


def main() -> None:
    products = load_products()
    today = date.today()
    history = {p["id"]: generate_series(p, today) for p in products}

    banner = (
        "// AUTO-GENERATED by ml/generate_price_history.py — do not hand-edit.\n"
        "// Re-run `python ml/generate_price_history.py` to regenerate (e.g. after\n"
        "// changing catalog prices in src/data/products.ts).\n\n"
        'import type { PricePoint } from "../types/product";\n\n'
        "export const GENERATED_PRICE_HISTORY: Record<string, PricePoint[]> = "
    )
    OUTPUT_TS.write_text(banner + json.dumps(history, indent=2) + ";\n", encoding="utf-8")
    print(f"Wrote {len(history)} product price histories -> {OUTPUT_TS}")


if __name__ == "__main__":
    main()
