import type { RecommendedIntervention } from "./pipelineTrace";
import { LEVER_POLICY, type InterventionSurface, type Intensity } from "./interventionPolicy";

export interface BrowsingCue {
  type: "search" | "product_view" | "review_dwell" | "spec_dwell" | "delivery_check" | "price_hover";
  query?: string;
  productId?: string;
  productName?: string;
  price?: number;
  category?: string;
  dwellSeconds?: number;
}

export interface BrowsingIntervention {
  intervention: RecommendedIntervention;
  surface: InterventionSurface;
  intensity: Intensity;
  actionUrl?: string;
  actionType?: "scroll_to_emi" | "open_reviews" | "open_comparison" | "open_delivery" | "apply_coupon";
}

export class BrowsingAgent {
  private lastTriggeredTime: number = 0;
  private cooldownMs: number = 3000;

  async evaluateCueAsync(cue: BrowsingCue): Promise<BrowsingIntervention | null> {
    const now = Date.now();
    if (now - this.lastTriggeredTime < this.cooldownMs) {
      return null;
    }

    try {
      const response = await fetch("http://localhost:8000/api/browsing-intent", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(cue),
      });

      if (response.ok) {
        const data = await response.json();
        if (data.status === "success" && data.recommended_lever_id) {
          this.lastTriggeredTime = now;
          const leverId = data.recommended_lever_id as keyof typeof LEVER_POLICY;
          const policy = LEVER_POLICY[leverId] ?? { intensity: 1, surface: "ambient" };
          return {
            intervention: {
              lever_id: data.recommended_lever_id,
              headline: data.headline || `Intervention for ${cue.type}`,
              rationale: data.rationale || "Generated by Browsing Intent Agent",
              score: 0.95,
              confidence: data.confidence || "high",
              expected_conversion_gain: 0.25,
              business_cost: "low",
              llm_endorsed: true,
              explanation: [
                {
                  factor: "browsing_intent",
                  observation: `Generated via Browsing Intent Agent (${data.agent_used || "Groq"})`,
                  contribution: 0.90,
                },
              ],
            },
            surface: policy.surface,
            intensity: policy.intensity,
            actionType: data.action_type || "open_reviews",
          };
        }
      }
    } catch (e) {
      console.warn("[BrowsingAgent] Backend fetch failed, using fallback:", e);
    }

    return this.evaluateCueSync(cue);
  }

  evaluateCueSync(cue: BrowsingCue): BrowsingIntervention | null {
    const now = Date.now();
    if (now - this.lastTriggeredTime < this.cooldownMs) {
      return null;
    }

    if (cue.type === "search" && cue.query) {
      const q = cue.query.toLowerCase();
      if (q.includes("phone") || q.includes("samsung") || q.includes("iphone") || q.includes("laptop") || q.includes("compare")) {
        this.lastTriggeredTime = now;
        return {
          intervention: {
            lever_id: "review_summary_surface",
            headline: `Compare top features for "${cue.query}"`,
            rationale: `See an AI breakdown of top buyer reviews and specs for ${cue.query} products.`,
            score: 0.95,
            confidence: "high",
            expected_conversion_gain: 0.25,
            business_cost: "low",
            llm_endorsed: true,
            explanation: [
              {
                factor: "search_intent",
                observation: `Active search for "${cue.query}" — comparing models`,
                contribution: 0.85,
              },
            ],
          },
          surface: LEVER_POLICY.review_summary_surface.surface,
          intensity: LEVER_POLICY.review_summary_surface.intensity,
          actionType: "open_comparison",
        };
      }
    }

    if (cue.type === "product_view") {
      if (cue.price && cue.price >= 5000) {
        this.lastTriggeredTime = now;
        return {
          intervention: {
            lever_id: "emi_plan_highlight",
            headline: "Split into No-Cost EMIs from ₹1,856/month",
            rationale: `Qualifies for 0% interest No-Cost EMI plans on eligible bank cards.`,
            score: 0.92,
            confidence: "high",
            expected_conversion_gain: 0.20,
            business_cost: "low",
            llm_endorsed: true,
            explanation: [
              {
                factor: "cart_value",
                observation: `High value product (₹${cue.price.toLocaleString("en-IN")}) qualifies for No-Cost EMI`,
                contribution: 0.78,
              },
            ],
          },
          surface: LEVER_POLICY.emi_plan_highlight.surface,
          intensity: LEVER_POLICY.emi_plan_highlight.intensity,
          actionType: "scroll_to_emi",
        };
      }
    }

    return null;
  }
}

export const browsingAgent = new BrowsingAgent();
